### ISSUE TITLE
*node not defined

### ISSUE THREAD

**Issue by Dextererials** [xlab/treeprint#19]
Following the code example "Iterating over the tree nodes" and because node is Unexported from treeprint package i cant use it in my main.go file
![image](https://user-images.githubusercontent.com/8620242/131179080-5efe6507-bb2e-4818-aa5f-e922c5a0d5b0.png)

**Comment by earlofhemsley** [comment]
I am also affected by this issue. Commenting to follow

**Comment by earlofhemsley** [comment]
I took 20 minutes and made a quick and dirty, slash and burn pull request for you. Feel free to merge it if you like. 

https://github.com/xlab/treeprint/pull/21

**Comment by xlab** [comment]
>  Feel free to merge it if you like.


I like! :D
Thanks

**Comment by xlab** [comment]
Also part of a new tag
https://github.com/xlab/treeprint/releases/tag/v1.2.0
