### ISSUE TITLE
strange tree

### ISSUE THREAD

**Issue by mattn** [xlab/treeprint#2]
This is output from command lile https://github.com/lileio/lile
```
$ find foo
foo/.gitignore
foo/.travis.yml
foo/Dockerfile
foo/Makefile
foo/foo/cmd/root.go
foo/foo/cmd/serve.go
foo/foo/cmd/subscribe.go
foo/foo/cmd/up.go
foo/foo/main.go
foo/foo.proto
foo/server/server.go
foo/server/server_test.go
foo/subscribers/subscribers.go
```

```
.
├── server
│   ├── server.go
│   └── server_test.go
├── subscribers
│   └── subscribers.go
├── foo
│   ├── cmd
│       ├── root.go
│       ├── serve.go
│       ├── subscribe.go
│       └── up.go
│   └── main.go
├── foo.proto
├── Makefile
├── Dockerfile
├── .travis.yml
└── .gitignore
```
maybe this is expected?
```
.
├── server
│   ├── server.go
│   └── server_test.go
├── subscribers
│   └── subscribers.go
├── foo
│   ├── cmd
│   │   ├── root.go
│   │   ├── serve.go
│   │   ├── subscribe.go
│   │   └── up.go
│   └── main.go
├── foo.proto
├── Makefile
├── Dockerfile
├── .travis.yml
└── .gitignore
```

**Comment by xlab** [comment]
Good catch, thanks!

**Comment by mattn** [comment]
Thanks for fixing this. BTW, why you use 0x00 0xa0 for indentation?

https://github.com/xlab/treeprint/blob/2075aa9cb861e96edf1e2eb375c555973f81e49e/treeprint.go#L164

On some character-set, for example japanese, it is shown as `?`.

![](http://go-gyazo.appspot.com/49f05a3b3f8e1e51.png)

**Comment by xlab** [comment]
It's expected to be Unicode friendly. As far as I can remember I use the same `tree` util uses.
Any ideas?

**Comment by mattn** [comment]
This is output on Windows. Do you want workaround fixes only on Windows?

**Comment by mattn** [comment]
One more thing. Corner string `⎿` is two cells on some locales.

**Comment by xlab** [comment]
This package will never be platform-specific, as its output is statically defined and may be parsed in logs during process mining.

The data it outputs is prevailing over the looks.

**Comment by mattn** [comment]
So you don't want fixing for east asian ambiguous widths. Right?

I don't have strong opinion about this. Just confirming how do you think. :)

**Comment by xlab** [comment]
I'm ready to fix any issue as long as it's universal for all possible platforms and locales. If we can replace the spacing char so it will work fine with Unicode and asian encodings then let's do it.

My point is that there should be no exception cases.

**Comment by mattn** [comment]
Most easy way to fix this issue is:

```diff
diff --git a/treeprint.go b/treeprint.go
index 467c87d..7412518 100644
--- a/treeprint.go
+++ b/treeprint.go
@@ -6,6 +6,9 @@ import (
 	"fmt"
 	"io"
 	"reflect"
+	"runtime"
+
+	"github.com/mattn/go-runewidth"
 )
 
 type Value interface{}
@@ -156,12 +159,25 @@ func printNodes(wr io.Writer,
 func printValues(wr io.Writer,
 	level int, levelsEnded []int, edge EdgeType, meta MetaValue, val Value) {
 
+	var edgeTypeLink, spaces string
+	if !runewidth.IsEastAsian() {
+		spaces = "   "
+		if runtime.GOOS == "windows" {
+			edgeTypeLink = string(EdgeTypeLink) + "   "
+		} else {
+			edgeTypeLink = string(EdgeTypeLink) + "   "
+		}
+	} else {
+		spaces = "       "
+		edgeTypeLink = string(EdgeTypeLink) + "     "
+	}
+
 	for i := 0; i < level; i++ {
 		if isEnded(levelsEnded, i) {
-			fmt.Fprint(wr, "    ")
+			fmt.Fprint(wr, spaces)
 			continue
 		}
-		fmt.Fprintf(wr, "%s   ", EdgeTypeLink)
+		fmt.Fprint(wr, edgeTypeLink)
 	}
 	if meta != nil {
 		fmt.Fprintf(wr, "%s [%v]  %v\n", edge, meta, val)
```

**Comment by mattn** [comment]
One another fix is using ASCII letters. For example `+` for `⎿`, `|` for `│`.

**Comment by xlab** [comment]
Okay, as the output of this utility is predictable, you could hand off both transformations to the application logic which can be OS-specific.

```go
tree := treeprint.New()
// do stuff
log.Println(applyFilter(tree.String()))

func applyFilter(str string) string {
    // uses github.com/mattn/go-runewidth
    // checks runtime.GOOS
    // replaces treeprint.EdgeTypeLink and other with mapped ASCII chars, etc
}
```

I will add link to this issue in README. Thanks for the solution.

**Comment by mattn** [comment]
I don't mind about fixing my apps. However, most of packages using treeprint will have to include this workaround.

**Comment by xlab** [comment]
Alternative to "workarounds" mentioned before: https://github.com/xlab/treeprint/commit/eee4a4aa121a53c4e81b37cd2a185d2167c6686e

There is a new fork that allows to override the chars to anything.
