### ISSUE TITLE
How can I code for printing the 'modified' tree that I show in this inquiry?

### ISSUE THREAD

**Issue by durimungsil** [xlab/treeprint#20]
Hello, 

According to your example of 'treeprint',  the following tree is printed and 
I understand the code to do this. (with treeprint v.1.1.0)

├── one
│   ├── subnode1
│   ├── subnode2
│   ├── two
│   │   ├── subnode1
│   │   ├── subnode2
│   │   └── three
│   │       ├── subnode1
│   │       └── subnode2
│   └── subnode3
└── outernode

Now, if I want to have the following tree structure, which is modified by me from the above, 

├── one
│   ├── subnode1
│   ├── subnode2
│   ├── two
│   │   ├── subnode1
│   │   ├── three
│   │   │   ├── subnode1
│   │   │   │   └──  sub-subnode A
│   │   │   └── subnode2
│   │   └── subnode2
│   └── subnode3
└── outernode

(Note: These two tree diagrams are distorted when I save (or upload) this posting.
If you copy the tree diagrams and paste into any text editor, then those diagram coudl not be distorted.)
   
how can I code for the modified tree above, using treeprint package???
(Actually, I already tried a lot, but I have not made it. )

Please give me the code for printing the modified tree above.

**Comment by ultra-whtbr** [comment]
I've got right results I wanted, through a lots of "trial-and-errors".  The key solution is to properly use "FindLastNode()". 
Anyway, this issue is just finished. The manageer of this issue board may completely delete or remove the current issue.
