### ISSUE TITLE
Custom treeprint.EdgeTypeStart

### ISSUE THREAD

**Issue by dastergon** [xlab/treeprint#4]
It would be great to add the ability for a custom`treeprint.EdgeTypeStart` root  instead of the  typical '.' (dot) character.

Thanks in advance,
Pavlos

**Comment by xlab** [comment]
@dastergon `treeprint.EdgeTypeStart` is a public variable, just set it.

**Comment by xlab** [comment]
Whoa sorry, should be a variable
