### ISSUE TITLE
There is no way to iterate or access the nodes

### ISSUE THREAD

**Issue by elliotchance** [xlab/treeprint#9]
I have a situation where I need to build a visual tree by traversing another tree in a specific order. The problem is I need to be able to find the immediate parent of a node with a meta. However, there is no way to walk up or down the tree.

The simplest solution is to just provide a method that flattens all nodes into a slice so it can be iterated.

Would you be open to adding another method to the `Tree` interface? If so I will put in a PR.

```go
// AllNodes returns the current node with all recursive children.
AllNodes() []Tree
```

**Comment by elliotchance** [comment]
Oh, and a non-recursive `Nodes() []Tree` that provides direct access to the children internally would also be useful.

**Comment by xlab** [comment]
@elliotchance if you put a PR that'd be nice! I'm bad at enumerating trees properly

**Comment by migueleliasweb** [comment]
@elliotchance Have a look at the PR I created. That should address your use case.

**Comment by c4milo** [comment]
@migueleliasweb, this is great! the only ask is to tag another version so I can bump it in my go.mod.

**Comment by migueleliasweb** [comment]
> @migueleliasweb, this is great! the only ask is to tag another version so I can bump it in my go.mod.

@c4milo, please +1 #18 🤟

**Comment by xlab** [comment]
Hey, just published
https://github.com/xlab/treeprint/releases/tag/v1.1.0

Thanks @migueleliasweb for all the improvements.
